#!/bin/bash
echo
echo Please select one of the following options:
echo
echo 'a = Add a record'
echo 'd = Delete a record'
echo
        read choice

                case $choice in
a) /root/scripts/addrecord;;
d) /root/scripts/deleterecord;;
*) echo Invalid choice - Bye.

                esac
