#!/bin/bash
# Desciption: This script will run basic admin tasks

echo
echo This script will run basic administrative commands
echo
top | head -10
echo
df -h
echo
free -m
echo
uptime
echo
echo End of script
