#!/bin/bash
# Description : This script will run basic linux tasks

echo
echo This script will run a few basic taks
echo
pwd
echo
ls
echo
whoami
echo
date
echo
cal
echo
touch a b c
echo End of the script
