#!/bin/bash
# Author: Name
# Date Created: 08/21/2020
# Description : Run basic linux tasks
# Date Modified: 08/21/2020

echo
echo This script will run a few basic taks
echo
pwd
echo
ls
echo
whoami
echo
date
echo
cal
echo
touch a b c
echo End of the script
