#!/bin/bash

# Description: This script will check whether the file exists or not

Files="/root/scripts/first.none
/root/scripts/third.none
/root/scripts/second.none"
echo
for i in $Files
do
	if [ ! -e $i ]
	then
	echo $i do not exist
	fi
done

