#!/bin/bash

# Description:  This script will check the disk space

a=`df -h | egrep -v "tmpfs|xvda1" | tail -n+2 | awk '{print $5}' | cut -d'%' -f1`
for i in $a
do
        if [ $i -ge 50 ]
        then
        echo Check disk space $i `df -h | grep $i`
        fi
done
