#!/bin/bash

# Description:  This script will ping the particular host

hosts="192.168.1.1"
ping -c1 $hosts &> /dev/null
        if [ $? -eq 0 ]
        then
        echo $hosts is OK
        else
        echo $hosts is NOT OK
        fi
