#!/bin/bash

# Description: This script will show the total time to assign permissions for multiple file

total=`ls -l java* | wc -l`
echo it will take $total seconds to assign permissions
echo
for i in java*
do
	chmod a+w $i
	sleep 1
done
