#!/bin/bash

# Description: This script used to trace the log

tail -fn0 /var/log/syslog | while read line


do


	echo $line | egrep -i "refused|invalid|error|fail|lost|shut|down|offline"


        if [ $? = 0 ]


        then


        echo $line >> /tmp/filtered-messages


        fi


done
