#!/bin/bash

# Description: This script will create mutliple files based on the user input

echo How many files do you want ?
read t
echo
echo Please enter the start name of the files ?
read  n
echo
for i in $(seq 1 $t)
do
	touch $n.$i
done

